# -*- coding: utf-8 -*-
"""business analyst live session.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMK7hhIQ8oECfg-nXFotCJ1PVxk_1oJ0

# **Project Title:** Sales Performance Analysis & Visualization in Python for Business Insights
"""



"""# **Define the Business Problem**

* A company wants to analyze last year’s sales data.
* Identify top-performing products and regions.
* Understand seasonal trends and profitability patterns.
"""



"""# **Defining the Project Objective**

* To Analyze sales performance accross regions and products.
* To Visualize Seasonal trends and profitibility patterns .
* Understand Sales vs Profit correlation.
* Generate Actionable business insights to optimize future sales.
"""



"""# **1️⃣ Import Libraries & Load Dataset**"""

# Install required libraries (if needed)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Read the uploaded CSV
df = pd.read_csv('/content/sales_data_2024.csv')

# Preview data
print(df.head())

"""# **Data Cleaning and Transformation**"""

print(df.info())

df['OrderDate'] = pd.to_datetime(df['OrderDate'])

print(df.info())

# Basic statistics
print(df.describe())

# Add Month & Year columns for trend analysis
df['YearMonth'] = df['OrderDate'].dt.to_period('M')

df.head()

"""# **3️⃣ Visualization in Python**"""



"""**A. Monthly Sales Trend (Line Chart)**"""

monthly_sales = df.groupby('YearMonth')['Sales'].sum().reset_index()
monthly_sales['YearMonth'] = monthly_sales['YearMonth'].astype(str)

plt.figure(figsize=(12,6))
sns.lineplot(x='YearMonth', y='Sales', data=monthly_sales, marker='o')
plt.xticks(rotation=45)
plt.title('Monthly Sales Trend in 2024')
plt.ylabel('Total Sales')
plt.show()



"""**B. Sales by Region (Bar Chart)**"""

region_sales = df.groupby('Region')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)

plt.figure(figsize=(8,5))
sns.barplot(x='Region', y='Sales', data=region_sales, palette='viridis')
plt.title('Total Sales by Region')
plt.ylabel('Sales')
plt.show()



"""**C. Top 10 Products by Sales**"""

product_sales = df.groupby('Product')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False).head(10)

plt.figure(figsize=(10,6))
sns.barplot(x='Sales', y='Product', data=product_sales, palette='mako')
plt.title('Top 10 Products by Sales')
plt.xlabel('Total Sales')
plt.show()



"""**D. Profit vs Sales (Scatter Plot)**"""

plt.figure(figsize=(10,6))
sns.scatterplot(x='Sales', y='Profit', data=df, hue='Region', palette='deep')
plt.title('Profit vs Sales by Region')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.show()



"""**E. Category-wise Sales (Pie Chart with Plotly)**"""

category_sales = df.groupby('Category')['Sales'].sum().reset_index()

fig = px.pie(category_sales, names='Category', values='Sales', title='Category-wise Sales Distribution')
fig.show()



"""# **4️⃣ Interactive Sales Dashboard (Plotly)**"""

import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Prepare summary data
monthly_sales = df.groupby('YearMonth')['Sales'].sum().reset_index()
monthly_sales['YearMonth'] = monthly_sales['YearMonth'].astype(str)

region_sales = df.groupby('Region')['Sales'].sum().reset_index()
product_sales = df.groupby('Product')['Sales'].sum().reset_index().sort_values('Sales', ascending=False).head(5)

# Create 2x2 interactive dashboard
fig = make_subplots(
    rows=2, cols=2,
    subplot_titles=(
        "Monthly Sales Trend",
        "Sales by Region",
        "Top 5 Products by Sales",
        "Profit vs Sales"
    )
)

# 1. Monthly Sales Trend
fig.add_trace(
    go.Scatter(x=monthly_sales['YearMonth'], y=monthly_sales['Sales'], mode='lines+markers', name='Monthly Sales'),
    row=1, col=1
)

# 2. Sales by Region
fig.add_trace(
    go.Bar(x=region_sales['Region'], y=region_sales['Sales'], name='Region Sales'),
    row=1, col=2
)

# 3. Top 5 Products by Sales
fig.add_trace(
    go.Bar(x=product_sales['Sales'], y=product_sales['Product'], orientation='h', name='Top Products'),
    row=2, col=1
)

# 4. Profit vs Sales Scatter
fig.add_trace(
    go.Scatter(x=df['Sales'], y=df['Profit'], mode='markers', marker=dict(color='purple', opacity=0.6), name='Profit vs Sales'),
    row=2, col=2
)

# Update layout
fig.update_layout(
    height=800, width=1000,
    title_text="📊 Business Analyst Sales Dashboard (Python)",
    showlegend=False
)

fig.show()



"""# **5️⃣ Conclusions and key Findings**

* East and North regions generate the highest revenue.
* Top products: Tablets and Monitors.
* Sales peak in May and August; dips in March and July.
* No direct correlation between high sales and high profit.
"""



"""# **6️⃣ Business Insights and Recommnedations**

1] Electronics are the main sales driver — keep them as a priority.

2] Accessories have potential for upselling and bundling with electronics.

3] Seasonal dips need further investigation — plan promotions to counter low months.

4] West region’s performance can be boosted with targeted marketing.

5] Review pricing and discount policies to avoid negative profit sales.
"""